# Generated by Django 5.2.4 on 2026-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
