# Generated by Django 5.2.4 on 2026-06-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_task_last_heartbeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_heartbeat',
        ),
    ]
